programming_languages = {
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "PHP",
    "Ruby",
    "Swift",
    "Go",
    "TypeScript",
    "Kotlin",
    "Lisp",
    "OCaml",
    "C",
    "C++",
    "Rust",
    "MATLAB",
    "Shell",
    "Dart",
    "Objective-C",
    "Perl",
    "Groovy",
    "Lua",
    "Haskell",
    "Assembly",
}

ignored_extensions = {"png", "jpg", "jpeg", "gif", "pdf", "zip", "js", "css", "ico"}
